#ifndef ELAWORKSPACE_ELAMETATYPE_ELAMETATYPEEXPORT_H_
#define ELAWORKSPACE_ELAMETATYPE_ELAMETATYPEEXPORT_H_

#include <QtCore/qglobal.h>

#ifdef ELAMETATYPE_LIBRARY
#define ELA_METATYPE_EXPORT Q_DECL_EXPORT
#else
#define ELA_METATYPE_EXPORT Q_DECL_IMPORT
#endif

#endif // ELAWORKSPACE_ELAMETATYPE_ELAMETATYPEEXPORT_H_
